### ISSUE TITLE
Json data feed - RSR project data not loading

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1010] opened 2016-08-11 15:14 UTC
@samvthom16 RSR updated to a new version earlier today & it looks like the RSR data on AKvo.org (and akvodev.org) is no longer loading.

https://github.com/akvo/akvo-rsr/releases/tag/v3.15  check 'under the hood'

http://akvo.org/seeithappen/all-rsr-project-updates/
http://akvo.org/seeithappen/
and the box at the bottom of the homepage 'latest rsr update' 

Not sure if the stats ont he counter of the new RSR product page is working as that may be using stored numbers.

Could you check it urgently please?

![screen shot 2016-08-11 at 17 09 26](https://cloud.githubusercontent.com/assets/2675262/17593595/b6b76436-5fe6-11e6-9813-6e1fbed22d0a.png)

**Comment by samvthom16** [comment] 2016-08-12 05:45
The problem is not with the API request but something to do with Json data plugin.

**Comment by Lynngre** [comment] 2016-08-12 06:13
@samvthom16 yes the old api has been rerouted with the same output so something is not working with the JSON plugin.  Could you try to figure out what please?

**Comment by samvthom16** [comment] 2016-08-12 15:54
@Lynngre The problem is with the template file. Looking into why this is happening only in the networkPage template.

**Comment by samvthom16** [comment] 2016-08-13 01:15
http://www.akvodev.org/seeithappen/ has been fixed by specifying the format as json in the shortcode.

**Closed** 2016-08-25 06:46 UTC
Labels: 1- Bug, 2 - JSON data plugin
